### ISSUE TITLE
brute forciing a list of domains with pure dns 

### ISSUE THREAD

**Issue by Bugspiderlee** [d3mondev/puredns#29] opened 2022-06-01 14:09 UTC
hie how i you thanks for the tool .was wondering if puredns have a flag to bruteforce multiple domains
like lets sya puredns -dL for a domain list
thanks

**Comment by d3mondev** [comment] 2023-03-28 04:32
Duplicate of #13

**Closed by d3mondev** 2023-03-28 04:32 UTC
